language: node_js
cache:
  directories:
    - 'node_modules'

notifications:
  email: mindreeper2420@gmail.com

node_js:
  - '10'

env:
  global:
    - COMMIT_AUTHOR_EMAIL: "mindreeper2420@gmail.com"
    - TRIGGER_REPO_SLUG: "mindreeper2420/prototype-template-react.github.io"
    - TRIGGER_REPO_BRANCH: "master"

before_script:
  - npm install -g yarn

script: yarn build
